### ISSUE TITLE
building from makefile

### ISSUE THREAD

**Issue by dawnlwoodard** [dawnlwoodard/hector_pf#4]
I was having trouble getting Hector to build from the makefile (or XCode for that matter, but I'd rather use the makefile) on the thaw-tracking and master branches on this fork (probably other branches as well, but these are the only ones I've tested). JGCRI's master branch works just fine for me with make. The first errors I fixed - I needed to set all the boost-related variables for my configuration - but then I got stuck on a linking error: 

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [hector] Error 1
make: *** [hector] Error 2

It's not urgent since I don't need this to debug the refreezing issue anymore, but if you have a chance to see if it works easily on your machine, it would be nice to know if the issue is on my end or more general. And/or if the error is something simple to fix.

**Comment by bpbond** [comment]
Sorry for the long delay here. This means that ld isn't finding the library to link to (almost certainly one of the build boost libraries). This doesn't happen for me.

**Comment by dawnlwoodard** [comment]
Okay, cool. Thanks for checking!
